from enum import Enum


class ApplicationCode(Enum):
    BL_STORAGE_FAILURE = "BL_STORAGE_FAILURE"
    BL_SECRET_FAILURE = "BL_SECRET_FAILURE"
    BL_LIST_BANKS_FAILURE = "BL_LIST_BANKS_FAILURE"
    BL_TOKEN_FAILURE = "BL_TOKEN_FAILURE"
    BL_INTERNAL_SERVER_ERROR = "BL_INTERNAL_SERVER_ERROR"
