from enum import Enum


class ApplicationCode(Enum):
    LAMBDA_BAD_REQUEST_ERROR = "LAMBDA_BAD_REQUEST_ERROR"
    LAMBDA_SECRET_FAILURE = "LAMBDA_SECRET_FAILURE"
    LAMBDA_WRITE_FILE_FAILURE = "LAMBDA_WRITE_FILE_FAILURE"
    LAMBDA_TOKEN_FAILURE = "LAMBDA_TOKEN_FAILURE"
    LAMBDA_POST_PAYMENT_FAILURE = "LAMBDA_POST_PAYMENT_FAILURE"
    LAMBDA_GET_PAYMENT_DETAILS_FAILURE = "LAMBDA_GET_PAYMENT_DETAILS_FAILURE"
    LAMBDA_INTERNAL_SERVER_ERROR = "LAMBDA_INTERNAL_SERVER_ERROR"
